baseURL = "http://fishwings.cn"
languageCode = "zh-CN"
title = "fishwings 博客"
theme = "maupassant-hugo"
googleAnalytics = ""  # UA-XXXXXXXX-X

## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
## 是否禁止URL Path转小写
disablePathToLower = true

hasCJKLanguage = true
summaryLength = 140

disqusShortname = "yourdiscussshortname"  ## 是否开启disqus评论，不要和utteranc同时开启

[author]
  name = "fishwings"

[params]
  author = "fishwings"
  subtitle = "专注于Go语言(golang)、云原生、分布式、大数据、项目管理、软件架构"
  keywords = "golang,go语言,fishwings,java,大数据,博客,云原生,分布式,软件架构,presto,OpenLooKeng"
  description = "专注于IT互联网，包括但不限于golang、java、大数据、云原生、分布式、presto、OpenLooKeng等"
  busuanzi = true #启用不算子网页统计
 # googleAd = ""  #ca-pub-xxxxxxxxxxxxxx
  localSearch = true # 启用本地搜索

  # 这里我存放在了主题的static文件夹里，根目录的似乎也可以
  customCSS = ['douban.css', 'other.css']
  # if ['custom.css'], load '/static/css/custom.css' file
  customJS = ['douban.js']
  # if ['custom.js'], load '/static/js/custom.js' file

  # 全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能
  toc = true  # 是否开启目录
  beian = "蜀ICP备2022004196号-1"
  fancybox = true
## 友情链接，可以多个

[[params.links]]
#  title = "飞雪无情的博客"
#  name = "飞雪无情的博客"
#  url = "https://www.flysnow.org/"
## 侧边栏广告位
#[[params.ads]]
#  title = "【渠道专享低折扣】11月特惠 限时2折"
#  url = "https://www.aliyun.com/acts/limit-buy?userCode=jdg9oj97"
#  img = "https://img.alicdn.com/tfs/TB1hblJl7Y2gK0jSZFgXXc5OFXa-750-400.jpg"

## 配置 utteranc评论,教程参考 https://utteranc.es/
[params.utteranc]
  enable = true
  repo = "your github repo" ##换成自己得
  issueTerm = "pathname"
  theme = "github-light"

## 开启版权声明，协议名字和链接都可以换
#[params.cc]
#    name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
#    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

## 配置代码高亮
[markup]
  [markup.highlight]
    lineNos = true
    style = "github"

## 配置网站菜单

[menu]

  [[menu.main]]
    identifier = "tools"
    name = "工具"
    url = "/tools/"
    weight = 2

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4
